name: Install dependencies
description: Install node modules and yarn dependencies

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - shell: bash
      run: |-
        yarn install --pure-lockfile
