const OAUTH_HOST = process.env.REACT_APP_OAUTH_HOST
const API_HOST = process.env.REACT_APP_API_HOST
const APP_VERSION = process.env.REACT_APP_VERSION
const APP_ENVIRONMENT = process.env.REACT_APP_ENVIRONMENT
const NODE_ENV = process.env.NODE_ENV
const SENTRY_DSN = process.env.REACT_APP_SENTRY_DSN

export {
  OAUTH_HOST,
  API_HOST,
  APP_VERSION,
  APP_ENVIRONMENT,
  NODE_ENV,
  SENTRY_DSN,
}
