import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Next App Boilerplate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="antialiased">
        <h1 className="text-5xl font-medium text-slate-900">
          Next App Boilerplate
        </h1>
      </main>
    </>
  )
}
